export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const FILTER_POSTS_BY_USER_ID_SUCCESS =
  "FILTER_POSTS_BY_USER_ID_SUCCESS";
export const CLEAN_POSTS_FILTERS_SUCCESS = "CLEAN_POSTS_FILTERS_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
